name: battery_stats
description: "Screen-on battery endurance sampling PoC."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
